#!/bin/sh
set -e
#remove the old backup
if [ -d "/usr/share/themes/DarK/backup" ]; then
	rm -rf /usr/share/themes/DarK/backup
fi

#check if we can choose dark as default theme
if [ ! -f /etc/gtk/gtkrc ]; then
	ln -s gtkrc.dark /etc/gtk/gtkrc
else
	if [ "$(readlink /etc/gtk/gtkrc)" = "gtkrc.dark" ]; then
		echo ""
	else
		(whiptail --msgbox 'Could not make Dark the default GTK theme because /etc/gtk/gtkrc already exists' 18 78)
	fi
fi
if [ ! -f /etc/gtk-2.0/settings.ini ]; then
	ln -s settings.ini.dark /etc/gtk-2.0/settings.ini
else
	if [ "$(readlink /etc/gtk-2.0/settings.ini)" = "settings.ini.dark" ]; then
		echo ""
	else
		(whiptail --msgbox 'Could not make Dark the default GTK2 theme because /etc/gtk-2.0/settings.ini already exists' 18 78)
	fi
fi
if [ ! -f /etc/gtk-3.0/settings.ini ]; then
	ln -s settings.ini.dark /etc/gtk-3.0/settings.ini
else
	if [ "$(readlink /etc/gtk-3.0/settings.ini)" = "settings.ini.dark" ]; then
		echo ""
	else
		(whiptail --msgbox 'Could not make Dark the default GTK3 theme because /etc/gtk-3.0/settings.ini already exists' 18 78)
	fi
fi

####change to distro colors!
unset _question
if command -v whiptail >/dev/null 2>&1; then
	if (whiptail --title "Change color?" --yesno "Would you like to try to change the theme color to your distros default theme/logo color)" 18 78); then
		 _question=y
	fi
	case $_question in
		[Yy])
			printf "\nSetting distribution colors ...\n"
			if [ -f /usr/share/themes/DarK/.changecolor.sh ]; then
				if dpkg --get-selections| grep debian-archive-keyring; then
					if dpkg --get-selections|grep kali-archive-keyring ;then
						_bg_color="#5488a7"
						_fg_color="#f2f1f1"
					elif dpkg --get-selections|grep parrot-archive-keyring ;then
						_bg_color="#056f6f"
						_fg_color="#f2f1f1"
					elif dpkg --get-selections|grep siduction-archive-keyring ;then
						_bg_color="#4c8bb6"
						_fg_color="#f2f1f1"
					elif dpkg --get-selections|grep kfreebsd ;then
						_bg_color="#bb2835"
						_fg_color="#f2f1f1"
					else 
						_bg_color="#d70a53"
						_fg_color="#f2f1f1"
					fi
					sh /usr/share/themes/DarK/.changecolor.sh -c "${_bg_color}" -c2 "${_fg_color}" || exit 0
				fi
				if dpkg --get-selections|grep bunsen-keyring ;then
						_bg_color="#cb961a"
						_fg_color="#f2f1f1"
					sh /usr/share/themes/DarK/.changecolor.sh -c "${_bg_color}" -c2 "${_fg_color}" || exit 0
				fi
				if dpkg --get-selections|grep cbpp-metapackage ;then
						_bg_color="#555250"
						_fg_color="#f2f1f1"
					sh /usr/share/themes/DarK/.changecolor.sh -c "${_bg_color}" -c2 "${_fg_color}" || exit 0
				fi
				if dpkg --get-selections|grep ubuntu-keyring ;then
					if dpkg --get-selections|grep lubuntu-default-settings ;then
						_bg_color="#918aaa"
						_fg_color="#f2f1f1"
					elif dpkg --get-selections|grep xubuntu-default-settings ;then
						_bg_color="#499bf1"
						_fg_color="#f2f1f1"
					elif dpkg --get-selections|grep ubuntustudio-default-settings ;then
						_bg_color="#499bf1"
						_fg_color="#f2f1f1"
					elif dpkg --get-selections|grep ubuntu-mate-default-settings ;then
						_bg_color="#87a556"
						_fg_color="#f2f1f1"
					else
						_bg_color="#f07746"
						_fg_color="#f2f1f1"
					fi
					sh /usr/share/themes/DarK/.changecolor.sh -c "${_bg_color}" -c2 "${_fg_color}" || exit 0
				fi
				if dpkg --get-selections|grep linuxmint-keyring ;then
					_bg_color="#90a876"
					_fg_color="#f2f1f1"
					sh /usr/share/themes/DarK/.changecolor.sh -c "${_bg_color}" -c2 "${_fg_color}" || exit 0
				fi
				if dpkg --get-selections|grep devuan-keyring ;then
					_bg_color="#7b7792"
					_fg_color="#f2f1f1"
					sh /usr/share/themes/DarK/.changecolor.sh -c "${_bg_color}" -c2 "${_fg_color}" || exit 0
				fi
			fi
		;;
		*)
			printf "skipping color change!\n"
		;;
	esac
fi
